"""Deterministic tax-adjustment calculations and gated account checks."""

from tax_risk.application.tax_adjustment_accounts.adjustment import (
    DONATION_LIMIT_RATE,
    PROFIT_TOTAL_LABEL,
    SALARY_ACCOUNT_MAX,
    SALARY_ACCOUNT_MIN,
    SALARY_EXCLUDED_ACCOUNTS,
    WELFARE_LIMIT_RATE,
    calculate_donation_adjustment,
    calculate_limited_tax_adjustment,
    calculate_welfare_adjustment,
    profit_total_label_matches,
    salary_account_is_in_scope,
)
from tax_risk.application.tax_adjustment_accounts.contracts import (
    AccountCheckRequest,
    AccountCheckResult,
    AdjustmentLabel,
    AdjustmentSubject,
    CheckStatus,
    CheckedAdjustmentDetail,
    CurrencyCheckSummary,
    DonationAdjustmentResult,
    MonthlyCheckSummary,
    SapIncomeRow,
    SettlementAdjustmentRow,
    TaxAdjustmentDecision,
    TrialBalanceRow,
    WelfareAdjustmentMonthlySummary,
    WelfareAdjustmentResult,
)
from tax_risk.application.tax_adjustment_accounts.donation import (
    DonationAdjustmentAccountCheckService,
    DonationAdjustmentCheckResult,
    SapIncomeSource,
)
from tax_risk.application.tax_adjustment_accounts.export import render_account_check_xlsx
from tax_risk.application.tax_adjustment_accounts.service import (
    SettlementAdjustmentSource,
    TaxAdjustmentAccountCheckService,
)
from tax_risk.application.tax_adjustment_accounts.welfare import (
    TrialBalanceSource,
    WelfareAdjustmentAccountCheckService,
    WelfareAdjustmentCheckResult,
)

__all__ = [
    "AccountCheckRequest",
    "AccountCheckResult",
    "AdjustmentLabel",
    "AdjustmentSubject",
    "CheckStatus",
    "CheckedAdjustmentDetail",
    "CurrencyCheckSummary",
    "DONATION_LIMIT_RATE",
    "DonationAdjustmentAccountCheckService",
    "DonationAdjustmentCheckResult",
    "DonationAdjustmentResult",
    "MonthlyCheckSummary",
    "PROFIT_TOTAL_LABEL",
    "SALARY_ACCOUNT_MAX",
    "SALARY_ACCOUNT_MIN",
    "SALARY_EXCLUDED_ACCOUNTS",
    "SapIncomeRow",
    "SapIncomeSource",
    "SettlementAdjustmentRow",
    "SettlementAdjustmentSource",
    "TaxAdjustmentAccountCheckService",
    "TaxAdjustmentDecision",
    "TrialBalanceRow",
    "TrialBalanceSource",
    "WELFARE_LIMIT_RATE",
    "WelfareAdjustmentAccountCheckService",
    "WelfareAdjustmentCheckResult",
    "WelfareAdjustmentMonthlySummary",
    "WelfareAdjustmentResult",
    "calculate_donation_adjustment",
    "calculate_limited_tax_adjustment",
    "calculate_welfare_adjustment",
    "profit_total_label_matches",
    "render_account_check_xlsx",
    "salary_account_is_in_scope",
]
